function t228__init(recid) {
    var rec = document.getElementById('rec' + recid); if (!rec) return; var menuBlock = rec.querySelector('.t228'); var mobileMenu = rec.querySelector('.t228__mobile'); var linkItems = rec.querySelectorAll('.t-menu__link-item'); linkItems = Array.prototype.slice.call(linkItems); var menuSubLinkItems = rec.querySelectorAll('.t-menusub__link-item'); var rightBtn = rec.querySelector('.t228__right_buttons_but .t-btn'); var mobileMenuPosition = mobileMenu ? mobileMenu.style.position || window.getComputedStyle(mobileMenu).position : ''; var mobileMenuDisplay = mobileMenu ? mobileMenu.style.display || window.getComputedStyle(mobileMenu).display : ''; var isFixedMobileMenu = mobileMenuPosition === 'fixed' && mobileMenuDisplay === 'block'; var overflowEvent = document.createEvent('Event'); var noOverflowEvent = document.createEvent('Event'); overflowEvent.initEvent('overflow', !0, !0); noOverflowEvent.initEvent('nooverflow', !0, !0); if (menuBlock) { menuBlock.addEventListener('overflow', function () { t228_checkOverflow(recid) }); menuBlock.addEventListener('nooverflow', function () { t228_checkNoOverflow(recid) }) }
    rec.addEventListener('click', function (e) { var targetLink = e.target.closest('.t-menusub__target-link'); if (targetLink && window.isMobile) { if (targetLink.classList.contains('t-menusub__target-link_active')) { if (menuBlock) menuBlock.dispatchEvent(overflowEvent) } else { if (menuBlock) menuBlock.dispatchEvent(noOverflowEvent) } } }); linkItems.forEach(function (linkItem) { linkItem.addEventListener('click', function () { if (linkItem.classList.contains('t-menusub__target-link') || linkItem.classList.contains('tooltipstered') || linkItem.classList.contains('t794__tm-link')) return; if (mobileMenu && isFixedMobileMenu) mobileMenu.click() }) }); Array.prototype.forEach.call(menuSubLinkItems, function (linkItem) { linkItem.addEventListener('click', function () { if (mobileMenu && isFixedMobileMenu) mobileMenu.click() }) }); if (rightBtn) { rightBtn.addEventListener('click', function () { if (mobileMenu && isFixedMobileMenu) mobileMenu.click() }) }
    if (menuBlock) { menuBlock.addEventListener('showME601a', function () { var menuLinks = rec.querySelectorAll('.t966__menu-link'); Array.prototype.forEach.call(menuLinks, function (menuLink) { menuLink.addEventListener('click', function () { if (mobileMenu && isFixedMobileMenu) mobileMenu.click() }) }) }) }
}
function t228_highlight() {
    var url = window.location.href; var pathname = window.location.pathname; if (url.substr(url.length - 1) === '/') { url = url.slice(0, -1) }
    if (pathname.substr(pathname.length - 1) === '/') { pathname = pathname.slice(0, -1) }
    if (pathname.charAt(0) === '/') { pathname = pathname.slice(1) }
    if (pathname === '') { pathname = '/' }
    var shouldBeActiveElements = document.querySelectorAll('.t228__list_item a[href=\'' + url + '\'], ' + '.t228__list_item a[href=\'' + url + '/\'], ' + '.t228__list_item a[href=\'' + pathname + '\'], ' + '.t228__list_item a[href=\'/' + pathname + '\'], ' + '.t228__list_item a[href=\'' + pathname + '/\'], ' + '.t228__list_item a[href=\'/' + pathname + '/\']'); Array.prototype.forEach.call(shouldBeActiveElements, function (link) { link.classList.add('t-active') })
}
function t228_checkAnchorLinks(recid) { if (window.innerWidth >= 980) { var rec = document.getElementById('rec' + recid); var navLinks = rec ? rec.querySelectorAll('.t228__list_item a[href*=\'#\']') : []; navLinks = Array.prototype.filter.call(navLinks, function (navLink) { return !navLink.classList.contains('tooltipstered') }); if (navLinks.length) { setTimeout(function () { t228_catchScroll(navLinks) }, 500) } } }
function t228_checkOverflow(recid) { var rec = document.getElementById('rec' + recid); var menu = rec ? rec.querySelector('.t228') : null; if (!menu) return; var mobileContainer = document.querySelector('.t228__mobile_container'); var mobileContainerHeight = t228_getFullHeight(mobileContainer); var windowHeight = document.documentElement.clientHeight; var menuPosition = menu.style.position || window.getComputedStyle(menu).position; if (menuPosition === 'fixed') { menu.classList.add('t228__overflow'); menu.style.setProperty('height', (windowHeight - mobileContainerHeight) + 'px', 'important') } }
function t228_checkNoOverflow(recid) { var rec = document.getElementById('rec' + recid); if (!rec) return !1; var menu = rec.querySelector('.t228'); var menuPosition = menu ? menu.style.position || window.getComputedStyle(menu).position : ''; if (menuPosition === 'fixed') { if (menu) menu.classList.remove('t228__overflow'); if (menu) menu.style.height = 'auto' } }
function t228_catchScroll(navLinks) { var clickedSectionID = null; var sections = []; var sectionToNavigationLinkID = {}; var interval = 100; var lastCall; var timeoutID; navLinks = navLinks.reverse(); navLinks.forEach(function (link) { var currentSection = t228_getSectionByHref(link); if (currentSection && currentSection.id) { sections.push(currentSection); sectionToNavigationLinkID[currentSection.id] = link } }); sections.sort(function (a, b) { return b.getBoundingClientRect().top - a.getBoundingClientRect().top }); t228_highlightNavLinks(navLinks, sections, sectionToNavigationLinkID, clickedSectionID); navLinks.forEach(function (navLink, i) { navLink.addEventListener('click', function () { var clickedSection = t228_getSectionByHref(navLink); if (!navLink.classList.contains('tooltipstered') && clickedSection && clickedSection.id) { navLinks.forEach(function (link, index) { if (index === i) { link.classList.add('t-active') } else { link.classList.remove('t-active') } }); clickedSectionID = clickedSection.id } }) }); window.addEventListener('scroll', function () { var dateNow = new Date().getTime(); if (lastCall && dateNow < lastCall + interval) { clearTimeout(timeoutID); timeoutID = setTimeout(function () { lastCall = dateNow; clickedSectionID = t228_highlightNavLinks(navLinks, sections, sectionToNavigationLinkID, clickedSectionID) }, interval - (dateNow - lastCall)) } else { lastCall = dateNow; clickedSectionID = t228_highlightNavLinks(navLinks, sections, sectionToNavigationLinkID, clickedSectionID) } }) }
function t228_getSectionByHref(curlink) { if (!curlink) return; var curLinkValue = curlink.href ? curlink.href.replace(/\s+/g, '') : ''; if (curLinkValue.indexOf('/') === 0) curLinkValue = curLinkValue.slice(1); if (curlink.href && curlink.matches('[href*="#rec"]')) { curLinkValue = curLinkValue.replace(/.*#/, ''); return document.getElementById(curLinkValue) } else { var selector = curlink.href ? curlink.href : ''; if (selector.indexOf('#') === 0 || selector.indexOf('/') === 0) selector = selector.slice(1); var fullSelector = '.r[data-record-type="215"] a[name="' + selector + '"]'; return document.querySelector(fullSelector) } }
function t228_highlightNavLinks(navLinks, sections, sectionToNavigationLinkID, clickedSectionID) {
    var scrollPosition = window.pageYOffset; var scrollHeight = Math.max(document.body.scrollHeight, document.documentElement.scrollHeight, document.body.offsetHeight, document.documentElement.offsetHeight, document.body.clientHeight, document.documentElement.clientHeight); var returnValue = clickedSectionID; var lastSection = sections.length ? sections[sections.length - 1] : null; var lastSectionTopPos = lastSection ? lastSection.getAttribute('data-offset-top') : '0'; lastSectionTopPos = parseInt(lastSectionTopPos, 10) || 0; if (sections.length && clickedSectionID === null && lastSectionTopPos > (scrollPosition + 300)) { navLinks.forEach(function (link) { link.classList.remove('t-active') }); return null }
    for (var i = 0; i < sections.length; i++) {
        var sectionTopPos = sections[i].getBoundingClientRect().top + window.pageYOffset; var navLink = sections[i].id ? sectionToNavigationLinkID[sections[i].id] : null; if (scrollPosition + 300 >= sectionTopPos || i === 0 && scrollPosition >= scrollHeight - window.innerHeight) {
            if (clickedSectionID === null && navLink && !navLink.classList.contains('t-active')) { navLinks.forEach(function (link) { link.classList.remove('t-active') }); if (navLink) navLink.classList.add('t-active'); returnValue = null } else if (clickedSectionID !== null && sections[i].id && clickedSectionID === sections[i].id) { returnValue = null }
            break
        }
    }
    return returnValue
}
function t228_setWidth(recid) { var rec = document.getElementById('rec' + recid); if (!rec) return; var menuCenterSideList = rec.querySelectorAll('.t228__centerside'); Array.prototype.forEach.call(menuCenterSideList, function (menuCenterSide) { menuCenterSide.classList.remove('t228__centerside_hidden') }); if (window.innerWidth <= 980) return; var menuBlocks = rec.querySelectorAll('.t228'); Array.prototype.forEach.call(menuBlocks, function (menu) { var maxWidth; var centerWidth = 0; var paddingWidth = 40; var leftSide = menu.querySelector('.t228__leftside'); var rightSide = menu.querySelector('.t228__rightside'); var menuList = menu.querySelector('.t228__list'); var mainContainer = menu.querySelector('.t228__maincontainer'); var leftContainer = menu.querySelector('.t228__leftcontainer'); var rightContainer = menu.querySelector('.t228__rightcontainer'); var centerContainer = menu.querySelector('.t228__centercontainer'); var centerContainerLi = centerContainer ? centerContainer.querySelectorAll('li') : []; var leftContainerWidth = t228_getFullWidth(leftContainer); var rightContainerWidth = t228_getFullWidth(rightContainer); var mainContainerWidth = mainContainer ? mainContainer.offsetWidth : 0; var dataAlign = menu.getAttribute('data-menu-items-align'); var isDataAlignCenter = dataAlign === 'center' || dataAlign === null; maxWidth = leftContainerWidth >= rightContainerWidth ? leftContainerWidth : rightContainerWidth; maxWidth = Math.ceil(maxWidth); Array.prototype.forEach.call(centerContainerLi, function (li) { centerWidth += t228_getFullWidth(li) }); if (mainContainerWidth - (maxWidth * 2 + paddingWidth * 2) > centerWidth + 20) { if (isDataAlignCenter) { if (leftSide) leftSide.style.minWidth = maxWidth + 'px'; if (rightSide) rightSide.style.minWidth = maxWidth + 'px'; if (menuList) menuList.classList.remove('t228__list_hidden') } } else { if (leftSide) leftSide.style.minWidth = maxWidth + ''; if (rightSide) rightSide.style.minWidth = maxWidth + '' } }) }
function t228_getFullWidth(el) { if (!el) return 0; var marginLeft = el.style.marginLeft || window.getComputedStyle(el).marginLeft; var marginRight = el.style.marginRight || window.getComputedStyle(el).marginRight; marginLeft = parseInt(marginLeft, 10) || 0; marginRight = parseInt(marginRight, 10) || 0; return el.offsetWidth + marginLeft + marginRight }
function t228_getFullHeight(el) { if (!el) return 0; var marginTop = el.style.marginTop || window.getComputedStyle(el).marginTop; var marginBottom = el.style.marginBottom || window.getComputedStyle(el).marginBottom; marginTop = parseInt(marginTop, 10) || 0; marginBottom = parseInt(marginBottom, 10) || 0; return el.offsetHeight + marginTop + marginBottom }
function t228_setBg(recid) { var rec = document.getElementById('rec' + recid); if (!rec) return; var menuBlocks = rec.querySelectorAll('.t228'); Array.prototype.forEach.call(menuBlocks, function (menu) { if (window.innerWidth > 980) { if (menu.getAttribute('data-bgcolor-setbyscript') === 'yes') { menu.style.backgroundColor = menu.getAttribute('data-bgcolor-rgba') } } else { menu.style.backgroundColor = menu.getAttribute('data-bgcolor-hex'); menu.setAttribute('data-bgcolor-setbyscript', 'yes'); if (menu.style.transform) menu.style.transform = ''; if (menu.style.opacity) menu.style.opacity = '' } }) }
function t228_appearMenu(recid) {
    if (window.innerWidth <= 980) return; var rec = document.getElementById('rec' + recid); if (!rec) return !1; var menuBlocks = rec.querySelectorAll('.t228'); Array.prototype.forEach.call(menuBlocks, function (menu) {
        var appearOffset = menu.getAttribute('data-appearoffset'); if (appearOffset) {
            if (appearOffset.indexOf('vh') !== -1) { appearOffset = Math.floor((window.innerHeight * (parseInt(appearOffset) / 100))) }
            appearOffset = parseInt(appearOffset, 10); var menuHeight = menu.clientHeight; if (typeof appearOffset === 'number' && window.pageYOffset >= appearOffset) { if (menu.style.transform === 'translateY(-' + menuHeight + 'px)') { t228_slideUpElement(menu, menuHeight, 'toBottom') } } else if (menu.style.transform === 'translateY(0px)') { t228_slideUpElement(menu, menuHeight, 'toTop') } else { menu.style.transform = 'translateY(-' + menuHeight + 'px)'; menu.style.opacity = '0' }
        }
    })
}
function t228_changebgopacitymenu(recid) { if (window.innerWidth <= 980) return; var rec = document.getElementById('rec' + recid); if (!rec) return; var menuBlocks = rec.querySelectorAll('.t228'); Array.prototype.forEach.call(menuBlocks, function (menu) { var bgColor = menu.getAttribute('data-bgcolor-rgba'); var bgColorAfterScroll = menu.getAttribute('data-bgcolor-rgba-afterscroll'); var bgOpacity = menu.getAttribute('data-bgopacity'); var bgOpacityTwo = menu.getAttribute('data-bgopacity-two'); var menuShadow = menu.getAttribute('data-menushadow') || '0'; var menuShadowValue = menuShadow === '100' ? menuShadow : '0.' + menuShadow; menu.style.backgroundColor = window.pageYOffset > 20 ? bgColorAfterScroll : bgColor; if (window.pageYOffset > 20 && bgOpacityTwo === '0' || window.pageYOffset <= 20 && bgOpacity === '0.0' || menuShadow === ' ') { menu.style.boxShadow = 'none' } else { menu.style.boxShadow = '0px 1px 3px rgba(0,0,0,' + menuShadowValue + ')' } }) }
function t228_createMobileMenu(recid) {
    var rec = document.getElementById('rec' + recid); if (!rec) return; var menu = rec.querySelector('.t228'); var burger = rec.querySelector('.t228__mobile'); if (burger) { burger.addEventListener('click', function () { if (burger.classList.contains('t228_opened')) { t228_fadeOut(menu, 300); burger.classList.remove('t228_opened') } else { t228_fadeIn(menu, 300, function () { if (menu.style.transform) menu.style.transform = ''; if (menu.style.opacity) menu.style.opacity = '' }); burger.classList.add('t228_opened') } }) }
    window.addEventListener('resize', t_throttle(function () { if (window.innerWidth > 980) { if (menu.style.opacity) menu.style.opacity = ''; if (menu.style.display === 'none') menu.style.display = '' } else if (menu.style.transform) menu.style.transform = '' }))
}
function t228_fadeOut(element, duration, callback) {
    if (!element) return !1; var opacity = 1; duration = parseInt(duration, 10); var speed = duration > 0 ? duration / 10 : 40; var timer = setInterval(function () {
        element.style.opacity = opacity; opacity -= 0.1; if (opacity <= 0.1) {
            element.style.opacity = '0'; element.style.display = 'none'; if (typeof callback === 'function') { callback() }
            clearInterval(timer)
        }
    }, speed)
}
function t228_fadeIn(element, duration, callback) {
    if (!element) return !1; if ((getComputedStyle(element).opacity === '1' || getComputedStyle(element).opacity === '') && getComputedStyle(element).display !== 'none') return !1; var opacity = 0; duration = parseInt(duration, 10); var speed = duration > 0 ? duration / 10 : 40; element.style.opacity = opacity; element.style.display = 'block'; var timer = setInterval(function () {
        element.style.opacity = opacity; opacity += 0.1; if (opacity >= 1) {
            element.style.opacity = '1'; if (typeof callback === 'function') { callback() }
            clearInterval(timer)
        }
    }, speed)
}
function t228_slideUpElement(menu, menuHeight, position) {
    var diff = position === 'toTop' ? 0 : menuHeight; var diffOpacity = position === 'toTop' ? 1 : 0; var timerID = setInterval(function () {
        menu.style.transform = 'translateY(-' + diff + 'px)'; menu.style.opacity = diffOpacity.toString(); diffOpacity = position === 'toTop' ? diffOpacity - 0.1 : diffOpacity + 0.1; diff = position === 'toTop' ? diff + (menuHeight / 20) : diff - (menuHeight / 20); if (position === 'toTop' && diff >= menuHeight) { menu.style.transform = 'translateY(-' + menuHeight + 'px)'; menu.style.opacity = '0'; clearInterval(timerID) }
        if (position === 'toBottom' && diff <= 0) { menu.style.transform = 'translateY(0px)'; menu.style.opacity = '1'; clearInterval(timerID) }
    }, 10)
}
function t552_init(recid, ratio) { var rec = document.getElementById('rec' + recid); var recordBlock = rec ? rec.querySelector('.t552') : null; t552__setHeight(recid, ratio); window.addEventListener('resize', t_throttle(function () { t552__setHeight(recid, ratio) })); if (typeof jQuery !== 'undefined') { $(recordBlock).on('displayChanged', function () { t552__setHeight(recid, ratio) }) } else { if (recordBlock) { recordBlock.addEventListener('displayChanged', function () { t552__setHeight(recid, ratio) }) } } }
function t552__setHeight(recid, ratio) { var rec = document.getElementById('rec' + recid); var firstIMG = rec.querySelector('.t552__blockimg'); var images = rec.querySelectorAll('.t552__blockimg'); Array.prototype.forEach.call(images, function (img) { var calculatedHeight = Math.floor(firstIMG.offsetWidth * ratio); img.style.height = calculatedHeight + 'px' }) }
